=== BackupTheBerlios/ntssapi-svn/NewTrueSharpSwordAPI/resourcen/Untitled1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Snowbird (wtg) -->
<!--W3C Schema generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="mirror">
		<xs:complexType>
			<xs:attribute name="location" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Amsterdam"/>
						<xs:enumeration value="AtlantaGA"/>
						<xs:enumeration value="Curitiba-Brazil"/>
						<xs:enumeration value="Duesseldorf-Germany"/>
						<xs:enumeration value="Irland"/>
						<xs:enumeration value="Ishikawa-Japan"/>
						<xs:enumeration value="Keihanna-Japan"/>
						<xs:enumeration value="Lausanne-Switzerland"/>
						<xs:enumeration value="McLean-Virginia"/>
						<xs:enumeration value="Moscow-Russia"/>
						<xs:enumeration value="Nordamerika"/>
						<xs:enumeration value="Paris-France"/>
						<xs:enumeration value="Saint-Petersburg-Russia"/>
						<xs:enumeration value="Seattle-Washington"/>
						<xs:enumeration value="Switzerland"/>
						<xs:enumeration value="Sydney-Australien"/>
						<xs:enumeration value="Tainan-Taiwan"/>
						<xs:enumeration value="University-of-Kent-UK"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="subdomain" type="xs:string" use="required"/>
			<xs:attribute name="suffix" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="mirrors">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="mirror" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="urlinfix" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="module">
		<xs:complexType>
			<xs:attribute name="filename" type="xs:string" use="required"/>
			<xs:attribute name="identifier" type="xs:string" use="required"/>
			<xs:attribute name="lang" type="xs:string" use="required"/>
			<xs:attribute name="language" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="revision" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="0"/>
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
						<xs:enumeration value="3"/>
						<xs:enumeration value="5"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="bible"/>
						<xs:enumeration value="dictionary"/>
						<xs:enumeration value="s-dictionary"/>
						<xs:enumeration value="x-quran"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="modules">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="module" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="repository">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="modules"/>
				<xs:element ref="mirrors"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="server" type="xs:anyURI"/>
	<xs:element name="zefania-modules">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="zefania-modules-list-servers"/>
				<xs:element ref="repository"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:decimal" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="zefania-modules-list-servers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="server"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BackupTheBerlios/ntssapi-svn/Modulliste/zefmod.xml
<?xml version="1.0"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Snowbird (wtg) -->
<?xml-stylesheet href="" type="text/xsl"?>
<zefania-modules version="1.10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\ZefaniaXML\SVN2\NewTrueSharpSwordAPI\resourcen\Untitled1.xsd">
	<zefania-modules-list-servers>
		<server>http://zefania-sharp.sourceforge.net</server>
	</zefania-modules-list-servers>
	<repository>
		<modules>
			<!-- === dictionaries ===================================== -->
			<module filename="en_en_torreys-topical-textbook_rev1.zip" identifier="TTB" lang="englisch" language="ENG" name="Torreys-Topical-Textbook" revision="1" type="s-dictionary"/>
			<module filename="kjv-lex_rev1.zip" identifier="kjv-lex" lang="englisch" language="ENG" name="Strong Dictionary King James" revision="1" type="s-dictionary"/>
			<module filename="sf_tcr_0_eng_full.zip" identifier="tct" lang="englisch" language="ENG" name="Thompson Chain Topics - ALPHA" revision="0" type="dictionary"/>
			<module filename="sf_smith_0_eng.zip" identifier="smith" lang="englisch" language="ENG" name="Smiths Bible Dictionary - ALPHA" revision="0" type="dictionary"/>
			<module filename="sf_robinson_0_eng.zip" identifier="robin" lang="englisch" language="ENG" name="Robinsons Morphological Analysis Codes " revision="0" type="dictionary"/>
			<module filename="DE_de_rieger_1b.zip" identifier="rieg" lang="deutsch" language="GER" name="Carl Heinrich Riegers Kommentar - BETA" revision="1" type="dictionary"/>
			<module filename="en_en_nave_3.zip" identifier="navetb" lang="englisch" language="ENG" name="Naves Topical Bible" revision="0" type="dictionary"/>
			<module filename="sf_easton_0_eng.zip" identifier="" lang="englisch" language="ENG" name="Easton Dictionary - ALPHA" revision="0" type="dictionary"/>
			<module filename="rwebster-lex_rev1.zip" identifier="RWebster-lex" lang="englisch" language="ENG" name="Strong Dictionary R.Webster" revision="1" type="s-dictionary"/>
			<module filename="luther1912-lex_rev1.zip" identifier="luth1912-lex" lang="deutsch" language="GER" name="Strong Dictionary Luther 1912" revision="1" type="s-dictionary"/>
			<module filename="elberfelder1905-lex_rev3.zip" identifier="elb1905-lex" lang="deutsch" language="GER" name="Strong Dictionary Elberfelder 1905" revision="3" type="s-dictionary"/>
			<module filename="elberfelder1871-lex_rev1.zip" identifier="elb1871-lex" lang="deutsch" language="GER" name="Strong Dictionary Elberfelder 1871" revision="1" type="s-dictionary"/>
			<!-- === GER ========================================= -->
			<module filename="sf_pattloch80.zip" identifier="pat80" lang="deutsch" language="GER" name="Pattloch Bibel" revision="1" type="bible"/>
			<module filename="sf_gruenewald1924.zip" identifier="gruen" lang="deutsch" language="GER" name="Grünewaldbibel 1924" revision="1" type="bible"/>
			<module filename="luther1912_strong_rev0.zip" identifier="luth1912+" lang="deutsch" language="GER" name="Luther 1912 mit Strongs" revision="0" type="bible"/>
			<module filename="sf_lu1546_rev1.zip" identifier="lu1546NT" lang="deutsch" language="GER" name="Luther 1546 (original) NT" revision="1" type="bible"/>
			<module filename="elberfelder1905-strongs_rev3.zip" identifier="elb1905str" lang="deutsch" language="GER" name="Elberfelder 1905 mit Strongs" revision="3" type="bible"/>
			<module filename="sf_de_DE_reinhardt1910_eva_0.zip" identifier="rei10ev" lang="deutsch" language="GER" name="Reinhardt 1910 Evangelien" revision="0" type="bible"/>
			<module filename="de_NDS_Daut_niee_Testament_en_de_Psalme_JFriesen_0_a.zip" identifier="DNTF" lang="deutsch" language="GER" name="Daut niee Testament" revision="1" type="bible"/>
			<module filename="DE_de_alemannische_1_nt.zip" identifier="almnt" language="GER" lang="deutsch" revision="1" name="Alemannische Bibel NT" type="bible"/>
			<module filename="de_NDS_ReimerNT2001_0_a.zip" identifier="ReimerNT" language="GER" lang="deutsch" name="Reimer 2001 NT" revision="0" type="bible"/>
			<module filename="fb2004_2005_01_08_r2.zip" identifier="fb2004" language="GER" lang="deutsch" name="FreeBible2004(08/01/05 http://www.flagsoft.ch/fb2004)" revision="2" type="bible"/>
			<module filename="sf_greber_nt.zip" identifier="GREB" lang="deutsch" language="GER" name="Greber 1936 NT" revision="0" type="bible"/>
			<module filename="sf_albrecht1926.zip" identifier="ALB" lang="deutsch" language="GER" name="Ludwig Albrecht NT 1926" revision="1" type="bible"/>
			<module filename="sf.knt2.zip" identifier="knt" lang="deutsch" language="GER" name="Konkordantes NT" revision="0" type="bible"/>
			<module filename="de_DE_Schlachter2000_1_NRS.zip" identifier="SCH2000NEU" lang="deutsch" language="GER" name="Schlachter 2000 neue Rechtschreibung" revision="1" type="bible"/>
			<module filename="de_DE_Schlachter2000_3_ARS.zip" identifier="SCH2000ars" lang="deutsch" language="GER" name="Schlachter 2000 alte Rechtschreibung" revision="3" type="bible"/>
			<module filename="sf_neue_revision_4.zip" identifier="NeÜ" lang="deutsch" language="GER" name="Neue evangelistische Übersetzung (Textstand 01.04.2006)" revision="4" type="bible"/>
			<module filename="sf_tafelbibel_rev1.zip" identifier="TAF" lang="deutsch" language="GER" name="Die Tafelbibel" revision="1" type="bible"/>
			<module filename="luther1912_rev1.zip" identifier="luth1912" lang="deutsch" language="GER" name="Luther 1912" revision="1" type="bible"/>
			<module filename="luther1912_apok_Rev1.zip" identifier="luth1912ap" lang="deutsch" language="GER" name="Luther 1912 mit Apokryphen" revision="1" type="bible"/>
			<module filename="Elberfelder_1905_Rev_5.zip" identifier="elb1905" lang="deutsch" language="GER" name="Elberfelder 1905" revision="5" type="bible"/>
			<module filename="sf_gerben.rev1.zip" identifier="Bible.GerBen" lang="deutsch" language="GER" name="Bengel NT" revision="1" type="bible"/>
			<module filename="luther1545_rev2.zip" identifier="luth1545" lang="deutsch" language="GER" name="Luther 1545" revision="2" type="bible"/>
			<module filename="Luther1545_rev1_Strong.zip" identifier="luth1545str" lang="deutsch" language="GER" name="Luther 1545 mit Strongs" revision="1" type="bible"/>
			<module filename="sf_elberfelder1871.zip" identifier="Bible.GerElb1871" lang="deutsch" language="GER" name="Elberfelder 1871" revision="0" type="bible"/>
			<module filename="schlachter1951_rev2.zip" identifier="sch1951" lang="deutsch" language="GER" name="Schlachter 1951" revision="2" type="bible"/>
			<module filename="schlachter1951_strong_rev0.zip" identifier="sch1951+" lang="deutsch" language="GER" name="Schlachter 1951 mit Strongs" revision="0" type="bible"/>
			<module filename="sf_koran_ger.zip" identifier="KORd" lang="deutsch" language="GER" name="Der Heilige Koran" revision="0" type="x-quran"/>
			<module filename="sf_nwue.zip" identifier="NWUE" lang="deutsch" language="GER" name="NWÜ deutsch" revision="0" type="bible"/>
			<module filename="sf_elb1871str_rev2.zip" identifier="elb1871strnt" lang="deutsch" language="GER" name="Elberfelder 1871 mit Strongs im NT" revision="2" type="bible"/>
			<!-- === ENG ===================================== -->
			
			<module filename="sf_common_rev_1.zip"  identifier="TCE" lang="englisch"  language="ENG" name="The Common Edition New Testament" revision="4" type="bible" ></module>
			<module filename="sf_diaglot_rev_1.zip"  identifier="Diaglot" lang="englisch"  language="ENG" name="Diaglot NT - 1865" revision="4" type="bible" ></module>
			<module filename="sf_leeser_rev1.zip" identifier="Leeser" lang="englisch" language="ENG" name="Leeser Old Testament - 1853" revision="1" type="bible"/>
			<module filename="sf_noyes_translation_rev1.zip" identifier="Noyes" lang="englisch" language="ENG" name="Noyes Translation (Job - Re) - 1869" revision="1" type="bible"/>
			
			<module filename="worsleys_nt_rev_1.zip" identifier="WORNT" lang="englisch" language="ENG" name="Worsleys NT" revision="1" type="bible"/>
			<module filename="KJC_NT_Rev_1.zip" identifier="KJVCNT" lang="englisch" language="ENG" name="King James Clarified NT" revision="1" type="bible"/>
			<module filename="Living_Oracles_NT_Rev_1.zip" identifier="LONT" lang="englisch" language="ENG" name="Living Oracles NT" revision="1" type="bible"/>
			<module filename="Revised_Young_Literal_Translation_NT_Rev_1.zip" identifier="RYLT-NT" lang="englisch" language="ENG" name="Revised Youngs Literal Translation NT" revision="1" type="bible"/>
			<module filename="en_gb_RWebster_1_Strong.zip" identifier="RWebster+" lang="englisch" language="ENG" name="Revised 1833 Webster Strongs" revision="1" type="bible"/>
			<module filename="en_gb_KJV2000_1.zip" identifier="KJV2000" lang="englisch" language="ENG" name="King James Version 2000" revision="1" type="bible"/>
			<module filename="en_gb_RWebster_1_ab.zip" identifier="RWebster" lang="englisch" language="ENG" name="Revised 1833 Webster Version" revision="1" type="bible"/>
			<module filename="en_GB_AConservativeVersion_0_a.zip" identifier="ACV" lang="englisch" language="ENG" name="A Conservative Version" revision="0" type="bible"/>
			<module filename="sf_a_wesley_nt.zip" identifier="Wesley's" lang="englisch" language="ENG" name="Wesleys New Testament (1755)" revision="0" type="bible"/>
			<module filename="sf_ukjv.zip" identifier="UKJV" lang="englisch" language="ENG" name="Updated King James Version" revision="0" type="bible"/>
			<module filename="sf_updv_2.zip" identifier="UPDV" lang="englisch" language="ENG" name="Updated Bible Version" revision="0" type="bible"/>
			<module filename="Geneva_rev1.zip" identifier="GB" lang="englisch" language="ENG" name="1599 Geneva Bible" revision="1" type="bible"/>
			<module filename="sf_rkjntb.zip" identifier="RKJVNT" lang="englisch" language="ENG" name="Revised King James NT" revision="0" type="bible"/>
